### ISSUE TITLE
Add ESLint?

### ISSUE THREAD

**Issue by pdehaan** [6a68/txp-metrics#3]
Did a quick audit locally with the following config and it came up with one potential issue (plus a bit of noise).

```yaml
env:
  browser: true
  es6: true
  node: true

extends:
  - eslint:recommended

globals:
  BroadcastChannel: false
  Components: false
  Services: false

rules:
  eqeqeq: error
  no-var: error
  prefer-const: error
  quotes: [error, single]
```

Installing ESLint locally and then running `$ eslint .` gives the following noise:

```
/Users/pdehaan/dev/github/mozilla/txp-metrics/txp-metrics.js
   64:23  error  Strings must use singlequote  quotes
   67:23  error  Strings must use singlequote  quotes
   74:26  error  'msg' is not defined          no-undef
   83:18  error  Empty block statement         no-empty
   93:15  error  Strings must use singlequote  quotes
  112:17  error  Strings must use singlequote  quotes
  115:17  error  Strings must use singlequote  quotes
  141:17  error  Strings must use singlequote  quotes
  148:19  error  Strings must use singlequote  quotes
  155:21  error  Strings must use singlequote  quotes
  158:27  error  Strings must use singlequote  quotes
  170:7   error  Unexpected console statement  no-console
  232:24  error  Strings must use singlequote  quotes
  234:24  error  Strings must use singlequote  quotes
  236:24  error  Strings must use singlequote  quotes
  240:17  error  Strings must use singlequote  quotes

✖ 16 problems (16 errors, 0 warnings)
```

The single quote issues are mainly about ESLint `quotes` rule not liking the template strings without any interpolated values. Pretty easy to auto convert to single quotes using `$ eslint . --fix` which reduces it to these 3 issues:

```sh
$  txp-metrics git:(master) ✗ npm run lint -- --fix

> txp-metrics@0.0.1 lint /Users/pdehaan/dev/github/mozilla/txp-metrics
> eslint . "--fix"


/Users/pdehaan/dev/github/mozilla/txp-metrics/txp-metrics.js
   74:26  error  'msg' is not defined          no-undef
   83:18  error  Empty block statement         no-empty
  170:7   error  Unexpected console statement  no-console

✖ 3 problems (3 errors, 0 warnings)
```

I think the only legit question is the use of the undefined `msg` variable in the [`sendEvent()` method](https://github.com/6a68/txp-metrics/blob/78e57166bdbe04f80ca54b27bf265d6a771c4d1c/txp-metrics.js#L74).
